# Generated by Django 3.2.18 on 2023-05-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230502_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_recent_login',
        ),
    ]
