# Generated by Django 3.2.18 on 2023-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_date_recent_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('M', '마스터'), ('A', '관리자'), ('U', '일반')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reject_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('W', '대기'), ('A', '승인'), ('R', '거절')], default='W', max_length=1),
        ),
    ]
