# Generated by Django 3.2.18 on 2023-05-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230502_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('W', '대기'), ('A', '승인'), ('R', '거절'), ('S', '탈퇴')], default='W', max_length=1),
        ),
    ]
