# Generated by Django 3.2.18 on 2023-04-30 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('expiration_date', models.DateField(null=True)),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
    ]
